name: Deploy Images to GHCR

on:
    push:
        tags:
            - 'v*.*.*'

env:
  PACKAGE_NAME: controly
  
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@main

            - name: 'Login to GitHub Container Registry'
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set env
              id: vars
              run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

            - name: echo
              run: echo ${{ steps.vars.outputs.tag }}

            - name: build image
              run: |
                  docker build . -t ghcr.io/simbafs/$PACKAGE_NAME:latest -t ghcr.io/simbafs/$PACKAGE_NAME:${{ steps.vars.outputs.tag }}

            - name: push image
              run: |
                  docker push ghcr.io/simbafs/$PACKAGE_NAME:${{ steps.vars.outputs.tag }}
                  docker push ghcr.io/simbafs/$PACKAGE_NAME:latest

            - name: Install pnpm
              uses: pnpm/action-setup@v4.1.0
              with: 
                version: 10

            - name: Install dependency 
              working-directory: countdown 
              run: pnpm install

            - name: Build
              working-directory: countdown 
              run: pnpm run build

            - name: Upload dist folder to GitHub Pages
              uses: actions/upload-pages-artifact@v3
              with:
                path: countdown/dist

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
                
